### ISSUE TITLE
Latest qBittorrent not pulled?

### ISSUE THREAD

**Issue by Sprooty** [DyonR/docker-qbittorrentvpn#107]
https://github.com/DyonR/docker-qbittorrentvpn/blob/5482282d621f46ff672d569787f9c09b9e9235db/Dockerfile#L139

Hi Dyron; any chance we can update this so later versions of qBitorrent are picked up?  The version been pulled 4.3.8 is now close to a year old.

Not sure why the latest version isn't been picked up looking at the code..

**Comment by DyonR** [comment]
The latest Docker `dyonr/qbittorrentvpn:latest` runs qBittorrent 4.4.3.1.  
Are you sure that you updated your container?

**Comment by DyonR** [comment]
![image](https://user-images.githubusercontent.com/16341409/182023075-2c066c4b-d900-4d08-8056-7a9ee4791fb3.png)

**Comment by Sprooty** [comment]
Thanks for checking DynoR; looks like i had my docker repos wrong.
