### ISSUE TITLE
Search plugins broken?

### ISSUE THREAD

**Issue by malventano** [DyonR/docker-qbittorrentvpn#114]
Newest image appeared to break search. While plugin .py files are still present in config, newest image shows no plugins installed and none can be added via the UI. If starting with empty plugin folder and attempting to add via UI, plugin files do appear to populate in the /data/nova3 folder, but UI continues to show no plugins.

**Comment by DyonR** [comment]
Are you sure Python is insalled?  
For me it is still working.
![image](https://user-images.githubusercontent.com/16341409/186462981-b6984f7a-c889-4070-bdb1-cc79d5b05c21.png)
  
  
Please add qbittorrent.log **REMOVE ANY SENSITIVE INFORMATION**

**Comment by malventano** [comment]
I have absolutely no idea how/why, but when I just went to repro again it's working perfectly. Maybe it pulls from some external site when used and that was temp down? I'm stumped, but it's working :).
Thanks for maintaining this container!

**Comment by DyonR** [comment]
Good to hear it's all good now! No problem 😄
