### ISSUE TITLE
Can WEBUI port be configurable as env var?

### ISSUE THREAD

**Issue by tiagorvmartins** [DyonR/docker-qbittorrentvpn#122]
Tried using both WEBUI_PORT and WEBUI_PORT_ENV but seems to not affecting anything, I still see the port 8080 being used in docker logs.

Also, even after changing manually the qBittorrent.conf in the volume itself, I can't access locally using the new port.

If I leave it as it is (using 8080), I dont have any issue, and can access from my lan network.

I am asking this, because I am trying to configure external access, tried port forwarding 8080 but without success. I believe the provider is blocking that router port cause its related to web servers, so trying a new one.

Thank you.

**Comment by ES-Six** [comment]
With docker you can use the publish option to publish a port to host and also redirect the port to another :
It's -p [destination_post:port_inside_container].

Exemple :
```bash
$ docker run  -d \
              -v /your/config/path/:/config \
              -v /your/downloads/path/:/downloads \
              -e "VPN_ENABLED=yes" \
              -e "VPN_TYPE=wireguard" \
              -e "LAN_NETWORK=192.168.0.0/24" \
here ->       -p 8042:8080 \
              --cap-add NET_ADMIN \
              --sysctl "net.ipv4.conf.all.src_valid_mark=1" \
              --restart unless-stopped \
              dyonr/qbittorrentvpn
```

In this exemple, the image has webui accessible to port the 8042 on the host but remain 8080 in the container.

Additionally, you can use your terminal capabilities to insert env vars as you probably use bash or shell if you run linux, so you can insert variable in the docker publish options if you really need it, like this :
```bash
$ docker run  -d \
              -v /your/config/path/:/config \
              -v /your/downloads/path/:/downloads \
              -e "VPN_ENABLED=yes" \
              -e "VPN_TYPE=wireguard" \
              -e "LAN_NETWORK=192.168.0.0/24" \
here ->       -p ${WEBUI_PORT}:8080 \
              --cap-add NET_ADMIN \
              --sysctl "net.ipv4.conf.all.src_valid_mark=1" \
              --restart unless-stopped \
              dyonr/qbittorrentvpn
```

**Comment by tiagorvmartins** [comment]
Alright thank you, the problem I was facing is that port forward can't reach the docker container, because container is linked to the ip 0.0.0.0 and not 127.0.0.1, I eventually fixed the problem with nginx. Thank you anyway! Closing now.

**Comment by chrisjenx** [comment]
Even with -p '8080:9091/tcp' I get "Unauthroized" looks like the webserver doesn't forward the request correctly if the port isn't matching

**Comment by shalak** [comment]
Just on a sidenote on changing the port. I'm running my container on macvlan network - thus it has its own IP. So I wanted to run the WebUI on 443 natively. There's no exposing ports on macvlan interfaces, so `-p 443:8080` wouldn't do anything.

I changed the port in qBittorrent GUI, but the default `iptables` in this image are blocking that anything, allowing only `8080`. Thankfully, there's `ADDITIONAL_PORTS` that can be used to allow the traffic.
