### ISSUE TITLE
exec /bin/bash: exec format error

### ISSUE THREAD

**Issue by billg118** [DyonR/docker-qbittorrentvpn#123]
Im trying to run this on a raspberry pi running 64-bit raspbian and Im getting this error after the container starts:

`exec /bin/bash: exec format error`

The container does start and it gets an IP for about a second, then this error happens.

Im using CLI with this command:

`sudo docker run --privileged  -d \
 --platform linux/amd64 \
              -v /home/bpi/dockerconfigs/:/config \
              -v /mnt/hdd3/Downloading/:/downloads \
              -e "VPN_ENABLED=yes" \
              -e "VPN_TYPE=wireguard" \
              -e "LAN_NETWORK=192.168.0.1/24" \
			  --cap-add NET_ADMIN \
              -p 8080:8080 \
              --restart unless-stopped \
              dyonr/qbittorrentvpn		  
`

I've tried everything I can find to fix this and I haven't been able to. This is incredibly annoying and I cant seem to figure it out.

Thoughts?

**Comment by DyonR** [comment]
I have no Raspberry Pi, but as far as I know, a Raspberry Pi is an ARM based system, and not a 'traditional' x86 or x86_64 system.  
I don't think Raspberry Pi can run x86/x86_64 applications.

**Comment by billg118** [comment]
Hey thanks for responding. I got confused by the arm/amd/aarch stuff. You're 100% correct. Marking this closed.
