### ISSUE TITLE
Python 3 Installs at every container start.

### ISSUE THREAD

**Issue by gderf** [DyonR/docker-qbittorrentvpn#135]
If **INSTALL_PYTHON3=yes** is set, then Python3 is installed every time the container starts, making startup slow.

Can Pythin3 be installed persistently instead?

**Comment by DyonR** [comment]
Python install is persistent. It should only reinstall after an update, or after you changed container configuration like environment variables. What system do you use?

**Comment by jpnoehre** [comment]
I don't know if this is related but the container keeps restarting because the health check fails. Network is working before it goes down though. I'm guessing the python package is used for checking the network health status?

Python also installs every time for me. I'm seeing this in my log:

```
2022-11-17 23:55:14.897623 [INFO] Python3 not yet installed, installing...
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/unstable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
E: Unable to locate package python3
```
