### ISSUE TITLE
Update to Qbittorrent 4.5.0

### ISSUE THREAD

**Issue by Rahzadan** [DyonR/docker-qbittorrentvpn#143]
Docker image still running on 4.4.5. Any planned update soon?

**Comment by DyonR** [comment]
Sure, I'll update it. Will let you know when the new image is live.

**Comment by DyonR** [comment]
New image is live on hub.docker.com.  
Update your container and it should be 4.5.0 👍🏻

**Comment by Rahzadan** [comment]
I noticed that it is 4.6.0 alpha1 and not 4.5.0.. I am using the **:latest** tag.

**Comment by DyonR** [comment]
You're right, something definitely went wrong. The build script should exclude alpha builds. I'll look into it. In my tes run it had no issue. I'll investigate.

**Comment by DyonR** [comment]
Fixed, again 😓   
Issue was caused by me running multiple build scripts at the same time, one for the :latest and one for :alpha  
I didnt take into account that they would interfere with each other.

**Comment by Rahzadan** [comment]
Seems good now. Thanks for such a quick turnaround!! Been loving the qbittorrent container with built-in VPN.
