### ISSUE TITLE
qbitorrent timing out/canceling operations?

### ISSUE THREAD

**Issue by musictrivianut** [DyonR/docker-qbittorrentvpn#145]
I can leave some logs/error messages later, if needed/wanted, but thought I would start by asking if anyone else is having issues with sonarr/radarr/lidarr connecting to qbittorrent recently.  I notice that the program was recently updated to version 4.5.0, but I also made some changes to my download file structure, so I'm trying to narrow down where the cause might be.  If no one else is experiencing this, I'll check my system further.  Thanks!

**Comment by DyonR** [comment]
I personally don't use qBittorrent in combination with sonarr/radarr/lidarr, so I can't look into this easily. 
Perhaps you can try to seek support at qBittorrent themselves? https://github.com/qBittorrent/qBittorrent

**Comment by musictrivianut** [comment]
Thanks, but think it was just my setup and the changes I had made.  Reverted and all seems to be working smoothly again.  Feel free to delete this.
