### ISSUE TITLE
Prefered Network?

### ISSUE THREAD

**Issue by Emporea** [DyonR/docker-qbittorrentvpn#147]
![image](https://user-images.githubusercontent.com/21969523/211172672-9c15ddc8-5408-4509-a070-ca232357ccfb.png)

There is this option. Do I need to assure its set on wg0 everytime so the traffic definitly goes through the vpn?

Is there a qbittorrent option to see the public IP that is used in the current session / connection?

**Comment by DyonR** [comment]
You don't need to change the network interface. 

If you wish to test to see what IP your torrent client is connecting with, you can use the Torrent Address Detection from https://ipleak.net/

**Comment by Emporea** [comment]
Thanks for the quick answer.
Is there a better way to permanently change settings in qbittorrent for example "download" and "temp-download" folder using docker / compose than just keeping the config in the volume / copy the whole config?

Amd how can I change the username and password for the web ui from docker environmental variables?
