### ISSUE TITLE
Is it possible to share the VPN Connection?

### ISSUE THREAD

**Issue by DieSchoeneWolke** [DyonR/docker-qbittorrentvpn#148]
Can I let other containers on the same network use the same IP adress from the VPN Provider?

**Comment by DyonR** [comment]
Yes! The qBittorrentVPN container can be used as a passthrough container. The passthroughvpn container is the same as the qbittorrent container, but with the qbittorrent stripped out of course.  
https://github.com/DyonR/docker-passthroughvpn contains an explanation on how to do this. If you run into issues, let me know
