### ISSUE TITLE
Update qBittorrent to 4.5.1

### ISSUE THREAD

**Issue by resech** [DyonR/docker-qbittorrentvpn#159]
qBittorrent 4.5.1 was released earlier this month, any chance of an update to pull in that version?

Thanks for all the work on this container!

**Comment by DyonR** [comment]
Container is updated :)

**Comment by cvaliente** [comment]
Hi @DyonR could you update the container to use qBittorrent 4.5.2 since 4.5.1&4.5.0 are affected by a security vulnerability. https://github.com/qbittorrent/qBittorrent/issues/18618

**Comment by DyonR** [comment]
> Hi @DyonR could you update the container to use qBittorrent 4.5.2 since 4.5.1&4.5.0 are affected by a security vulnerability. [qbittorrent/qBittorrent#18618](https://github.com/qbittorrent/qBittorrent/issues/18618)

The security vulnerability does not affect Linux or Docker, and the container should be updated already.

**Comment by cvaliente** [comment]
@DyonR thanks a lot. I was not so much concerned about the vulnerability itself but that trackers have started banning the affected versions. The trackers don't see/care whether that version is running in docker or linux :)
