### ISSUE TITLE
Stuck in restart loop "Network is possibly down"

### ISSUE THREAD

**Issue by KingKoehler** [DyonR/docker-qbittorrentvpn#162]
This has worked fine for at least a few months since I changed anything with my docker containers. However, recently after re-activating my Mullvad subscription (not on autopay), I noticed qbittorent wasn't working properly. I'd assume it had something to do with the VPN since I can't think of what else changed, but I didn't change any of the devices or the wireguard config file. I didn't do anything except pay for an extra month. No new devices have been added or removed since September. The last time qbittorrent had been used successfully for me was February 20th, and I have not come back to it until now.

Assuming I'm messing something up, any idea what's wrong?

Logs:
Here is what is in qbitorrent.log (redacting what I think is sensitive?)
at the start:
> (N) 2023-03-02T04:23:12 - qBittorrent v4.5.2 started
(N) 2023-03-02T04:23:12 - Using config directory: /config/qBittorrent/config
(N) 2023-03-02T04:23:13 - Trying to listen on the following list of IP addresses: "0.0.0.0:55027,[::]:55027"
(I) 2023-03-02T04:23:13 - Peer ID: "-qB4520-"
(I) 2023-03-02T04:23:13 - HTTP User-Agent: "qBittorrent/4.5.2"
(I) 2023-03-02T04:23:13 - Distributed Hash Table (DHT) support: ON
(I) 2023-03-02T04:23:13 - Local Peer Discovery support: ON
(I) 2023-03-02T04:23:13 - Peer Exchange (PeX) support: ON
(I) 2023-03-02T04:23:13 - Anonymous mode: OFF
(I) 2023-03-02T04:23:13 - Encryption support: ON
(I) 2023-03-02T04:23:13 - UPnP/NAT-PMP support: ON
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "127.0.0.1". Port: "TCP/55027"
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "127.0.0.1". Port: "UDP/55027"
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "[redacted]". Port: "TCP/55027"
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "[redacted]". Port: "UDP/55027"
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "172.19.0.4". Port: "TCP/55027"
(I) 2023-03-02T04:23:13 - Successfully listening on IP. IP: "172.19.0.4". Port: "UDP/55027"

then it goes through torrents, and at the end:
> (I) 2023-03-02T04:23:13 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Wed Feb 1 01:23:30 2023.
(N) 2023-03-02T04:23:13 - Using built-in Web UI.
(W) 2023-03-02T04:23:13 - Couldn't load Web UI translation for selected locale (C).
(N) 2023-03-02T04:23:13 - Web UI: Now listening on IP: *, port: 8080
(W) 2023-03-02T04:23:23 - Couldn't download IP geolocation database file. Reason: The remote host name was not found (invalid hostname)
(N) 2023-03-02T04:23:34 - WebAPI login success. IP: ::ffff:172.19.0.9
(N) 2023-03-02T04:23:46 - WebAPI login success. IP: ::ffff:172.19.0.7
(W) 2023-03-02T04:25:49 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP: no router found"
(W) 2023-03-02T04:25:49 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP: no router found"
(W) 2023-03-02T04:25:49 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP: no router found"
(N) 2023-03-02T04:36:40 - WebAPI login success. IP: ::ffff:172.19.0.1
Catching signal: SIGTERM
Exiting cleanly
(N) 2023-03-02T04:37:20 - qBittorrent termination initiated
(I) 2023-03-02T04:37:20 - UPnP/NAT-PMP support: OFF

Docker log:
https://gist.github.com/KingKoehler/e194be1f430052944f7216f0c0a2d7cd

**Comment by KingKoehler** [comment]
I resolved by just deleting the wireguard config file I've used since August and creating a new one. Changed nothing else. Not sure what went wrong for that to fix it.

**Comment by MYanello** [comment]
I had the same issue and fix. It was because my wg0 keys got rotated by my vpn provider
