### ISSUE TITLE
wg-quick: `wg0' already exists

### ISSUE THREAD

**Issue by polds** [DyonR/docker-qbittorrentvpn#18]
Hello, I ran into an interesting issue where restarting a container caused wireguard to not come back up with the error `wg-quick: 'wg0' already exists`. In my case the container had exceeded memory limits I had imposed and restarted itself and then entered into a crash loop.

Could we down the wg connection before trying to up it again? Either that or catch the error from  https://github.com/DyonR/docker-qbittorrentvpn/blob/master/openvpn/start.sh#L267 ?

**Comment by DyonR** [comment]
I've made a change to the DyonR/docker-qbittorrentvpn:dev branch which includes a `wg-quick down` before running `wg-quick up`.  Hopefully this fixes the issues, if so, I will merge it into the master branch.
The Docker container is still building on Docker Hub. I'll let you know when this build is finished.  
When it's finished you can switch from the `latest` to `dev` Docker (the are no differences between the branches but that), and see if that fixes the issue.  
I'll get back to you when building is done 😄

**Comment by polds** [comment]
Thanks for such a quick response! It's worth noting (on my system at least) that downing a connection that isn't there is also an error:

```
$ wg-quick down wg0 && echo $?
1
```

The change you made still may need to catch that so it doesn't error on first spin up.

**Comment by DyonR** [comment]
You're right. I didn't think about wg-quick throwing exit code one. I'll work on that and let you know when it's finished 👍

**Comment by DyonR** [comment]
Alright, should be good now, please try the `dev` branch from Docker.  
This is the like I added; https://github.com/DyonR/docker-qbittorrentvpn/blob/dev/openvpn/start.sh#L267

**Comment by polds** [comment]
Using the `dev` tag seems to work! I'm no longer getting a crash loop. Thanks!

**Comment by DyonR** [comment]
It's merged into master now, so if building the Docker image is done, you can switch back to the `latest` docker tag 😃
