### ISSUE TITLE
How can I specify which server to connect to?

### ISSUE THREAD

**Issue by OnlyC0RE** [DyonR/docker-qbittorrentvpn#184]
How can I set a specific server location for my PVN to connect to?
I use PIA and I can't go above 11MB/s.

**Comment by DyonR** [comment]
Really depends on your VPN Provider.  
For example, I use Windscribe and they give out a config per server location  
![image](https://github.com/DyonR/docker-qbittorrentvpn/assets/16341409/0d6588c9-10c6-420e-b316-55211fbddb2e)

**Comment by OnlyC0RE** [comment]
Ah, so I have to download a config file from PIA?
Looks like it comes in a .ovpn format? Or is this something different?
What should I do now with this file? place it in a config folder and specify it in docker-compose?

**Comment by DyonR** [comment]
I am honestly not familiar with docker-compose, but in the container should have access to a volume called `/config`.  
Then the .ovpn file must be placed in /config/openvpn/OPENVPN_FILE.ovpn

**Comment by OnlyC0RE** [comment]
Alright! I'll do that. Thanks for the super fast replies ;)

**Comment by DyonR** [comment]
You're welcome! If you need more directions, feel free to ask
