### ISSUE TITLE
ERROR: Cannot Open /dev/net/tun

### ISSUE THREAD

**Issue by Arturoe1** [DyonR/docker-qbittorrentvpn#39]
Freshly pulled image. 
OpenVPN can not start critical error: 

Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

NET_ADMIN has been  provided.

**Comment by DyonR** [comment]
You must run the container with privileged mode, for the easiest solution.  
  
If you really do not wish to run it privileged, you can try to also add --device=/dev/net/tun to the `docker run` command.  
`--cap-add=NET_ADMIN --device=/dev/net/tun`

**Comment by Arturoe1** [comment]
nope doesn't work even with priviledged mode, i don't know what else do.
 docker run --privileged  -d  -v /volume1/Docker/qBittorrent_TEST/config:/config -v /volume1/Download:/downloads -e "VPN_ENABLED=yes"-e "VPN_TYPE=openvpn"  -e "LAN_NETWORK=192.168.0.0/24" -p 8080:8080  dyonr/qbitt


2021-03-07 15:10:17.841045 [INFO] VPN_OPTIONS not defined (via -e VPN_OPTIONS)
2021-03-07 15:10:17.879062 [INFO] Adding 1.1.1.1 to resolv.conf
2021-03-07 15:10:17.915804 [INFO] Adding 8.8.8.8 to resolv.conf
2021-03-07 15:10:17.952821 [INFO] Adding 1.0.0.1 to resolv.conf
2021-03-07 15:10:17.989549 [INFO] Adding 8.8.4.4 to resolv.conf
2021-03-07 15:10:18.024031 [INFO] PUID not defined. Defaulting to root user
2021-03-07 15:10:18.058738 [INFO] PGID not defined. Defaulting to root group
2021-03-07 15:10:18.093621 [INFO] Starting OpenVPN...
Sun Mar  7 15:10:18 2021 WARNING: file 'credentials.conf' is group or others accessible
Sun Mar  7 15:10:18 2021 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Sun Mar  7 15:10:18 2021 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
Sun Mar  7 15:10:18 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxxxxx:xxxx
Sun Mar  7 15:10:18 2021 UDP link local: (not bound)
Sun Mar  7 15:10:18 2021 UDP link remote: [AF_INET]xxxxxxx:xxxx
Sun Mar  7 15:10:18 2021 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Sun Mar  7 15:10:18 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1569'
Sun Mar  7 15:10:18 2021 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
Sun Mar  7 15:10:18 2021 WARNING: 'comp-lzo' is present in local config but missing in remote config, local='comp-lzo'
Sun Mar  7 15:10:18 2021 [server] Peer Connection Initiated with [AF_INET]xxxxxxx:xxxx
Sun Mar  7 15:10:19 2021 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Sun Mar  7 15:10:19 2021 Exiting due to fatal error

**Comment by Arturoe1** [comment]
Quick update, found the error: 
My ASUSTOR NAS did not have the interface tun created. 

I created the interface and now the container works flawlessly. 

Thank you for yuour support!
