### ISSUE TITLE
Access web-ui from External IP

### ISSUE THREAD

**Issue by pooryamoh** [DyonR/docker-qbittorrentvpn#43]
Hi,
I can successfully access web-ui from localhost:8080, but I can't access web-ui from external IP, I tried reverse proxy on nginx but it doesn't work properly, How can achieve this?
## Run command
```
docker run --privileged   \
              -v /root/config/:/config \
              -v /downloads:/downloads \
              -e "VPN_ENABLED=yes" \
              -e "VPN_TYPE=openvpn" \
              -e "LAN_NETWORK=192.168.0.0/24" \
              -p 8080:8080 \
              --restart unless-stopped \
              dyonr/qbittorrentvpn
```

**Comment by DyonR** [comment]
Did you portforward port 8080 in your own router?

**Comment by DyonR** [comment]
No response or more info provided. Closing this issue. Please open a new one if you still experience problems.
