### ISSUE TITLE
Function to create torrent

### ISSUE THREAD

**Issue by ciasis** [DyonR/docker-qbittorrentvpn#45]
Hey guys,
not a real issue here, but is there a function/way to create a torrent anywhere in qBittorent? I can't find it.
Other than that, awesome work, I really love your container. Works superbly!

**Comment by DyonR** [comment]
This is something directly related to qBittorrent and not my container. But I can still answer your question, it's not possible to make a torrent from the WebUI.  
For more info or support regarding this, check out this Issue on the qBittorrent project page https://github.com/qbittorrent/qBittorrent/issues/5614
