### ISSUE TITLE
dos2unix: problems renaming

### ISSUE THREAD

**Issue by LsHallo** [DyonR/docker-qbittorrentvpn#48]
```
dos2unix: problems renaming '/config/openvpn/d2utmpB6lt2C' to '/config/openvpn/be.ovpn': Device or resource busy
qbittorrent    |           output file remains in '/config/openvpn/d2utmpB6lt2C'
qbittorrent    | dos2unix: problems converting file /config/openvpn/be.ovpn
```

what is dos2unix trying to achieve?
it can't overwrite the config since I'm also using the same config in other containers.
how can i disable dos2unix?
or maybe change dos2unix that it only converts to a temp file inside the container?

**Comment by DyonR** [comment]
I think OpenVPN has issues if the format of the file is wrong, so dos2unix converts the file from Windows (CRLF) to LF

**Comment by LsHallo** [comment]
I ran dos2unix outside of the container to convert the file and it still does not work...
What else can I try?
Weird is, that my other 2 containers with ovpn can work with the config no problem.

**Comment by DyonR** [comment]
Does your container have read and write permissions to the ovpn file?

**Comment by LsHallo** [comment]
Yes it does. But as said before the config is in use by 2 other containers. So probably not writable since it is in use.

**Comment by DyonR** [comment]
Easy workaround for now would be to make a copy of the ovpn directory and place it somewhere else and map that to your container. I'll do some testing to see if dos2unix is really necessary

**Comment by LsHallo** [comment]
Ok I'm out of ideas...
Container environment:
`PUID=1000`
`PGID=1000`
Config file on host is 777 with owner 1000:1000
Mounted with `"/opt/vpn/be/be.conf:/config/openvpn/be.ovpn"`
Still crying about the file it cannot write..

**Comment by DyonR** [comment]
The problem is most likely that you mounted the file directly instead of via a directory

**Comment by LsHallo** [comment]
Ok that worked. Thanks!
