### ISSUE TITLE
[Docs] Wireguard with IPv6

### ISSUE THREAD

**Issue by mchangrh** [DyonR/docker-qbittorrentvpn#49]
When wireguard has IPv6 enabled, the IPv6 range has to be added to `-e "LAN_NETWORK` and a parameter passed into docker: 
`--sysctl net.ipv6.conf.all.disable_ipv6=0` otherwise the container will stop with error `RTNETLINK answers permission denied`

**Comment by athphane** [comment]
For me it was a weird "creating interface" and "deleting interface" loop. Adding the sysctl parameter fixed it all up.
