### ISSUE TITLE
4.3.5 Does not allow adding of search plugins

### ISSUE THREAD

**Issue by mikul9** [DyonR/docker-qbittorrentvpn#51]
When adding search engines go to 
Search->Search Plugins...->Install New Plugin
In plugin path enter either a URL or local path (e.g. https://gist.github.com/sa3dany/1478e311e6371a60e251e7bdfc2dda65/raw/6288d84627e23823427d03f7aca2f492aa0c8338/one337x.py or /config/plugins/one337xpy)
Hit Ok.

Result:
Nothing happens. No plug in is added. No entry is made into the log.

**Comment by DyonR** [comment]
Did you set the environment variable INSTALL_PYTHON3 to yes?
For me it works fine.

![image](https://user-images.githubusercontent.com/16341409/127387187-521f9ccf-8e54-41e6-a2ff-3e3081e31efd.png)

**Comment by mikul9** [comment]
I did not have that set, so I set it and it now refuses to connect to my VPN. Removing the variable or changing it to 'no' doesn't resolve the issue. Is there a way to undo the Python 3 install and confirm the version that I'm working under?

**Comment by DyonR** [comment]
> I did not have that set, so I set it and it now refuses to connect to my VPN. Removing the variable or changing it to 'no' doesn't resolve the issue. Is there a way to undo the Python 3 install and confirm the version that I'm working under?

To remove Python, you need to reinstall the container.  
run `docker container ls -a`, look for the qbittorrentvpn container, copy the name (for example `qbittorrentvpn`)
`docker stop qbittorrentvpn`
`docker rm qbittorrentvpn`  
Run / pull the container again.  
  
Python should not interfere with the VPN connection though...

**Comment by mikul9** [comment]
Thank you for the information. The tech from PureVPN told me that they don’t support Python 3 which doesn’t make sense. They haven’t been the easiest VPN service to deal with.





On Jul 29, 2021, at 2:03 PM, DyonR ***@***.***> wrote:


I did not have that set, so I set it and it now refuses to connect to my VPN. Removing the variable or changing it to 'no' doesn't resolve the issue. Is there a way to undo the Python 3 install and confirm the version that I'm working under?

To remove Python, you need to reinstall the container.
run docker container ls -a, look for the qbittorrentvpn container, copy the name (for example qbittorrentvpn)
docker stop qbittorrentvpn
docker rm qbittorrentvpn
Run / pull the container again.

Python should not interfere with the VPN connection though...

**Comment by DyonR** [comment]
Python can not interfere with OpenVPN or WireGuard, since it's something that is completely separate from it.  
If you set `INSTALL_PYTHON3` to `yes` and try to install the plugin it should work.  
Can you post the log of the docker so I can see why I doesn't connect?
