### ISSUE TITLE
Suggestion: VPN_ENABLED should be checked against yes|no and fail if wrong

### ISSUE THREAD

**Issue by francois-pasquier** [DyonR/docker-qbittorrentvpn#65]
I made a mistake using `true` as the value for `VPN_ENABLED`, I had no idea I was not using the VPN.

What do you think about throwing an error and preventing qbittorrent to run if `VPN_ENABLED` isn't equal to `yes|no`?

**Comment by DyonR** [comment]
Good suggestion, I will change this in the next update. Note that I currently do not have a lot of time to work on my containers, but if I find some time, I'll definitely add this.
