### ISSUE TITLE
"Checking resume data" when restarting image

### ISSUE THREAD

**Issue by brandonvu99** [DyonR/docker-qbittorrentvpn#69]
Hey everyone,

Whenever my docker container gets restarted (due to, typically, restarting my computer), all my torrents go through a "Checking resume data" phase. I assume that it's checking every single file to make sure it's not corrupted, but checking tons of data every reboot sounds unnecessary on my hard drive.

I've searched around a bit for people with similar issues, and a lot of them seem to be pointing to corruption of the `.fastresume` file. [Here is someone who documented their fix from 2018](https://github.com/qbittorrent/qBittorrent/issues/15381#issuecomment-912080617), which basically says that if qBittorrent doesn't have a clean exit, the `.fastresume` files may get corrupted. To test that, I've tried the docker command `docker stop --time=3000 xxxxxxxxx`, but the only logs that show up in docker were:
```
2021-10-13 01:09:42.273151 [INFO] Network is up

2021-10-13 01:14:47.331183 [INFO] Network is up
```
and no logs in `/config/qBittorrent/data/logs` pop up after I issue the command.

So, I'm wondering if there is a good way to stop the docker container gracefully, just as an initial test to see if a graceful shutdown (something akin to clicking `File > Quit` in the Windows version of qBittorrent) could fix this issue.

Thanks in advance and I'm sorry if this question is out of scope for this project!

OS: Windows 10
Docker Version: 4.0.1

**Comment by DyonR** [comment]
I am aware of this. It is the behaviour of qBittorrent.  
Unsafe shutdown => Check all files again.  
  
I don't think there is a 'nice' way to stop a Docker container, if someone knows how to, let me know.
