### ISSUE TITLE
qbittorrent-nox failing to start with the latest docker image.

### ISSUE THREAD

**Issue by jxmorrow** [DyonR/docker-qbittorrentvpn#70]
Watchtower just updated me to the latest image from DockerHub. I'm not seeing new commits since last month, so I assume this is just a qBittorrent version increment. What I'm seeing when running the new image is qbittorrent-nox is never starting. Interestingly, the container log indicates that it is running (while not having a PID):

- 2021-10-31 20:38:44.655173 [INFO] Starting qBittorrent daemon...
- Logging to /config/qBittorrent/data/logs/qbittorrent.log.
- 2021-10-31 20:38:45.705398 [INFO] qBittorrent PID: 
- 2021-10-31 20:38:45.724647 [INFO] Started qBittorrent daemon successfully...

May be a logic problem in that PID check. 

Anyhow, the most telling part is in the qbittorrent.log file. The new lines (post-update) are these:

- /usr/local/bin/qbittorrent-nox: error while loading shared libraries: libQt5Sql.so.5: cannot open shared object file: No such file or directory
- /usr/local/bin/qbittorrent-nox: error while loading shared libraries: libQt5Sql.so.5: cannot open shared object file: No such file or directory
- /usr/local/bin/qbittorrent-nox: error while loading shared libraries: libQt5Sql.so.5: cannot open shared object file: No such file or directory

I suspect that may be one line per attempt to start. These lines are not present elsewhere in the log file before updating, so I suspect this is where the problem lies. Please let me know if there's anything else I should look at or other info that might be helpful.

**Comment by dessalines** [comment]
Downgrading to `dyonr/qbittorrentvpn:legacy_iptables` fixed this for the time being.

**Comment by onednasty** [comment]
Can confirm this issue and workaround by setting repository to dyonr/qbittorrentvpn:legacy_iptables.

**Comment by alikej** [comment]
> Can confirm this issue and workaround by setting repository to dyonr/qbittorrentvpn:legacy_iptables.

Me too

**Comment by DyonR** [comment]
New Docker is building, will let you know when it's published so you know when you can update the container. Will take 10-20 minutes

**Comment by DyonR** [comment]
New Docker is published to the Docker Hub, had some issues when creating it, so it took a bit longer than expected.  

----

The issue was mainly caused by the `Dockerfile` not excluding `rc` releases of qBittorrent. This caused that `qbittorrent-4.4.0rc1` was used when building the container instead of the new `qbittorrent-4.3.9` version.  
The `rc1` version did require an additional dependency which is now added (for future purposed).
This container should run the latest stable version of qBittorrent and not `beta` or `rc`.

**Comment by alikej** [comment]
still unable to load web UI

> New Docker is published to the Docker Hub, had some issues when creating it, so it took a bit longer than expected.
> 
> The issue was mainly caused by the `Dockerfile` not excluding `rc` releases of qBittorrent. This caused that `qbittorrent-4.4.0rc1` was used when building the container instead of the new `qbittorrent-4.3.9` version. The `rc1` version did require an additional dependency which is now added (for future purposed). This container should run the latest stable version of qBittorrent and not `beta` or `rc`.

**Comment by DyonR** [comment]
You can open the console and run `apt update && apt -y install libqt5sql5`  
After that restart the container
