### ISSUE TITLE
Qbittorent not working after last update (maybe related to #70)

### ISSUE THREAD

**Issue by riddertommie** [DyonR/docker-qbittorrentvpn#71]
maybe related to #70 but not sure.

qBittorrentvpn not working after last update, 6 hours ago via auto update (watchtower) cant acces via webpage anymore neither via sonarr, radarr, etc.

No error in the logfile.
Logfile ending with [INFO] Network is up.
Some warnings in log but no big thinks.

Went back from image: **dyonr/qbittorrentvpn** to image: **dyonr/qbittorrentvpn:v4_2_x** and working again.

**Comment by jxmorrow** [comment]
In your container log (the one that shows the network up message), do you have a line where it should be showing the PID, but it's actually just a blank? If so, that's probably the same thing. You can also check the actual qBT log file (referenced in the container log) and see if it shows the same library file missing errors I observed. For example, mine is located within the container at /config/qBittorrent/data/logs/qbittorrent.log.

**Comment by DyonR** [comment]
I am aware of the issue and currently investigating

**Comment by DyonR** [comment]
I am sure this is related to #71, closing.

**Comment by riddertommie** [comment]
Thanks!
