### ISSUE TITLE
Wireguard VPN stopped working - Can't figure it out

### ISSUE THREAD

**Issue by arjones85** [DyonR/docker-qbittorrentvpn#77]
When restarting my container, it always ends with:

qbittorrent-vpn    | 2021-11-30 12:32:38.358332 [ERROR] Network is down, exiting this Docker

I have regenerated the config multiple times from Torguard's website and replaced the wg0.conf file with the new one. If I configure the container to not use the VPN, it starts fine and I am able to ping out to the internet without an issue. When trying a manual wg-quick up ./wg0.conf, I cannot ping 8.8.8.8/1.1.1.1. 

How do I get more details wireguard logs out of this container so that I can troubleshoot further?

Thanks!

**Comment by arjones85** [comment]
For anyone else that runs into this issue, I have ended up separating the VPN and QBittorrent jobs into separate containers. Get linuxserver/wireguard and linuxserver/qbittorrent, add the wireguard service as the network for qbittorrent, and be done.

**Comment by Iceboy-6** [comment]
I have same problem and I am using Torguard wireguard generator too. I will investigate further on this, maybe comparing Torguard's .conf against other VPN .conf. Maybe something on Torguard's .conf is blocking container connection.

**Comment by Iceboy-6** [comment]
> For anyone else that runs into this issue, I have ended up separating the VPN and QBittorrent jobs into separate containers. Get linuxserver/wireguard and linuxserver/qbittorrent, add the wireguard service as the network for qbittorrent, and be done.

@arjones85 Hi! Could you please share your docker-compose config? I am trying to configure wireguard + qbit, but without any luck. I will share it later here, but I add service: wireguard to qbit's network
