### ISSUE TITLE
It would be useful to provide a wg0.conf example

### ISSUE THREAD

**Issue by JOduMonT** [DyonR/docker-qbittorrentvpn#78]

**Comment by DyonR** [comment]
wireguard configs are created by wireguard, so I shouldn't really need to provide an example, just like I do not provide an exmaple for openvpn.  
Nevertheless, here is a wireguard config from my VPN provider, Windscribe, with fake private and public keys, and fake IPs (except for the endpoint);  
```
[Interface]
PrivateKey = 2M4kUYORVAYrpD8UXqV4WlOboKg3QCpkwx4Hl+HlCWk=
Address = 1.2.3.4/32
DNS = 1.2.3.5

[Peer]
PublicKey = nxfqi+mlqkvyBZ50lC1jd+tse49qFonoSIc/bL4+o2Q=
AllowedIPs = 0.0.0.0/0
Endpoint = ams-193-wg.whiskergalaxy.com:65142
PresharedKey = ED2Gy6y54rAbCCjGBimXsrjivO+0c6IGjFErK2B38m8=
```

**Comment by aparis2002** [comment]
As a VPN client, for a VPN provider where every time you connect you get a dynamic (different) IP address (i.e. you don't have a static IP address), what IP would you enter under [Interface] -> Address? Can it be random? (I will always add the /32 as a VPN client)
