### ISSUE TITLE
Setting ENABLE_SSL to something else than 'yes' does nothing

### ISSUE THREAD

**Issue by DyonR** [DyonR/docker-qbittorrentvpn#88]
If you want to disable SSL, you would normally set ENABLE_SSL to 'no' or something similar, but this doesn't change any of the qBittorrent configuration files at the moment.
Therefore, once SSL is enabled, you cannot disable it anymore, unless you manually change the config file and set `WebUI\HTTPS\Enabled=true` to `false`

**Comment by M-archand** [comment]
> Therefore, once SSL is enabled, you cannot disable it anymore, unless you manually change the config file and set WebUI\HTTPS\Enabled=true to false

Hi DyonR. I have run into the issue you mentioned above and couldn't log in to my Web UI after mistakenly setting ENABLE_SSL to yes. I was previously able to log in to the Web UI before messing around with the settings and defining ENABLE_SSL as 'yes'. 

When I update my config file to contain `WebUI\HTTPS\Enabled=false` and then redeploy my container without the ENABLE_SSL environment variable present, my config file is being overwritten and setting `WebUI\HTTPS\Enabled=true`, and once again giving me a 'secure connection failed' error when I try to use the Web UI. I am not sure why this is, perhaps a docker caching thing that I'm not aware of, as I'm new to docker.

The only way I was able to remedy this was by deleting my /config volume and setting a new one then redeploying. I doubt this helps you in any way but just wanted to mention my solution in case anyone else runs in to the same problem.

**Comment by DyonR** [comment]
I've a bit of spare time in my hands, so I'll look into fixing this issue now 😁 Hopefully I can push out an update with a working ENABLE_SSL setting in a 1-2 hours
